services:

  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hapi-fhir:
    image: robferguson/hapi-fhir-au:7.6.0
    build: .
    container_name: hapi-fhir
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hapi
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_DRIVERCLASSNAME: 'org.postgresql.Driver'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect'
    ports:
      - 80:80
    configs:
      - source: hapi
        target: /app/config/application.yaml

volumes:
  postgres_data:
    driver: local

configs:
  hapi:
    # file: ./hapi.application.yaml
    file: hapi.application-fhir-au-core-1.0.0-preview.yaml
