services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hapi-fhir:
    build: .
    container_name: hapi-fhir
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml

volumes:
  postgres_data:
    driver: local

configs:
  hapi:
    # file: ./hapi.application.yaml
    file: ./hapi.application-fhir-au.yaml
