server:
  max-http-request-header-size: 64KB
spring:
  ai:
    mcp:
      server:
        enabled: true
  main:
    banner-mode: off
hapi:
  fhir:
    fhir_version: R4
    tester:
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
    implementationguides:
      au_core:
        name: hl7.fhir.au.core
        version: 1.0.0-preview
        reloadExisting: false
        installMode: STORE_AND_INSTALL
        packageUrl: https://hl7.org.au/fhir/core/1.0.0-preview/package.tgz
        fetchDependencies: true
    logical_urls:
      - http://hl7.org.au/*
