hapi:
  fhir:
    default_encoding: json
    implementationguides:
      au_core:
        name: hl7.fhir.au.core
        version: 0.4.1-preview
        reloadExisting: false
        installMode: STORE_AND_INSTALL
        packageUrl: https://hl7.org.au/fhir/core/0.4.1-preview/package.tgz
        fetchDependencies: true
    logical_urls:
      - http://hl7.org.au/*
