server:
  max-http-request-header-size: 64KB
spring:
  main:
    banner-mode: off
hapi:
  fhir:
    server_address: 'http://localhost:8080/fhir'
    refuse_to_fetch_third_party_urls: false
    fhir_version: R5
