server:
  max-http-request-header-size: 64KB
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hapi-fhir
    username: admin
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
      search_index_full_text_enabled: false
