hapi:
  fhir:
    default_encoding: json
    ig_runtime_upload_enable: true
    enable_repository_validating_interceptor: true
    implementationguides:
      au-core:
        name: hl7.fhir.au.core
        version: 1.0.0-ci-build
        reloadExisting: true
        installMode: STORE_AND_INSTALL
        packageUrl: https://build.fhir.org/ig/hl7au/au-fhir-core/package.tgz
        fetchDependencies: true
